container:
  gitlab_image: gitlab/gitlab-ee:16.8.2-ee.0
  name: gitlab
  hostname: gitlab.example.com
  env:
    GITLAB_HOME: ~/gitlab-home
  gitlab_config:
    GITLAB_OMNIBUS_CONFIG: "external_url 'http://{{ hostvars[inventory_hostname].inventory_hostname }}'"
