- name: Prepare Gitlab instance
  hosts: git_group

  tasks:
    - name: Create home folder for Gitlab
      file:
        path: "{{ gitlab_container.env.GITLAB_HOME}}"
        state: directory
    - name: Run Gitlab instance in Docker
      shell: |
        docker run --detach \
          --hostname {{ gitlab_container.hostname }} \
          --name {{ gitlab_container.name }} \
          --publish 443:443 --publish 80:80 --publish 2222:22 \
          --restart always \
          --volume $GITLAB_HOME/config:/etc/gitlab \
          --volume $GITLAB_HOME/logs:/var/log/gitlab \
          --volume $GITLAB_HOME/data:/var/opt/gitlab \
          --shm-size 256m \
          {{ gitlab_container.image }}
      environment: "{{ gitlab_container.env }}"
    - name: Install libraries for Gitlab python
      pip:
        name: python-gitlab
