- name: Add Gitlab repositories for testtest user
  hosts: git_group

  tasks:
    - name: Wait for Gitlab running
      shell: while [ "`docker inspect -f \{\{.State.Health.Status\}\} gitlab`" != "healthy" ]; do sleep 2; done
    - name: Create new repositories (Inventory, Billing, Api Gateway, Infrastructure) for the user
      gitlab_project:
        api_url: "http://{{ hostvars[inventory_hostname].inventory_hostname }}"
        api_username: "{{ admin.username }}"
        api_password: "{{ password }}"
        name: "{{ item }}"
        state: present
      loop:
        - "Inventory-app"
        - "Billing-app"
        - "Api-gateway-app"
        - "Infrastructure-configuration"
      register: created_projects
    - name: Extract project IDs and store in a list
      set_fact:
        project_ids: "{{ created_projects.results | json_query('[].project.id') }}"
