- name: Prepare Gitlab instance
  hosts: git_group

  tasks:
    - name: Create home folder for Gitlab
      file:
        path: "{{ container.env.GITLAB_HOME }}"
        state: directory
    - name: Install library for Docker python
      pip:
        name: requests
    - name: Run Gitlab instance in Docker
      community.docker.docker_container:
        detach: true
        name: "{{ container.name }}"
        image: "{{ container.gitlab_image }}"
        hostname: "{{ container.hostname }}"
        ports:
          - "443:443"
          - "80:80"
          - "2222:22"
        restart_policy: "always"
        volumes:
          - "{{ container.env.GITLAB_HOME }}/config:/etc/gitlab"
          - "{{ container.env.GITLAB_HOME }}/logs:/var/log/gitlab"
          - "{{ container.env.GITLAB_HOME }}/data:/var/opt/gitlab"
        shm_size: "256M"
        env: "{{ container.gitlab_config }}"
    - name: Install libraries for Gitlab python
      pip:
        name: python-gitlab
